get-flash-videos: whitelist prerelease
The Big Sur rebottling of this formula failed with:

  ==> brew audit get-flash-videos --online --git --skip-style
  ==> FAILED
  get-flash-videos:
    * 1.25.99.03 is a GitHub pre-release.
  Error: 1 problem in 1 formula detected

It looks like this project is moribund but when it was active homebrew
tracked the prereleases regularly.  Probably the easiest thing to do
for the moment is just whitelist this one so it can keep building.